[package]

name = "ivancerust"
version = "0.0.1"
authors = ["ivan ceras <ivanceras@gmail.com>"]

[dependencies.time]
git = "https://github.com/rust-lang/time"


[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
